"""Global constants and algorithm IDs for PPNO."""

# Algorithm IDs
ALGORITHM_UH = 0
ALGORITHM_DE = 1
ALGORITHM_DA = 2
ALGORITHM_NSGA2 = 3
ALGORITHM_DIRECT = 4
ALGORITHM_MOEAD = 5
ALGORITHM_MACO = 6
ALGORITHM_PSO = 7

# Optimization parameters
PENALTY_VALUE = 1e9
MAX_RETRIES = 3
MAX_ALGORITHM_TIME = 300

# Local Search (FLS-H) Settings
LS_MAX_ITER = 50
LS_ACCEPTANCE_THRESHOLD = 0.01
LS_NEIGHBORHOOD_SIZE = 20
