"""Local Search Refiner for Hydraulic Optimization.

This module implements the Feasible Local Search – Hybrid (FLS-H) algorithm
to improve solutions generated by metaheuristics or heuristics in pipe network
optimization problems.
"""

import logging
import numpy as np
from typing import Any, List, Dict, Tuple, Optional

# Logger configuration
logger = logging.getLogger(__name__)


class LocalRefiner:
    """Implements the FLS-H (Feasible Local Search – Hybrid) algorithm.

    Attributes:
        simulation: An instance of the Optimization class.
        max_iter (int): Maximum number of iterations for the refinement.
        acceptance_threshold (float): Percentage (decimal) of allowed worsening (e.g., 0.01 for 1%).
        cache (Dict[bytes, Any]): Evaluation cache to avoid redundant simulations.
    """

    def __init__(self, simulation: Any, config: Optional[Dict[str, Any]] = None):
        """Initializes the LocalRefiner.

        Args:
            simulation: The Optimization instance to use for evaluations.
            config: Optional configuration dictionary.
        """
        self.simulation = simulation
        config = config or {}
        self.max_iter = config.get('max_iter', 50)
        self.acceptance_threshold = config.get('acceptance_threshold', 0.01)
        self.neighborhood_size = config.get('neighborhood_size', 20)
        self.cache = {}

    def refine(self, x0: np.ndarray) -> np.ndarray:
        """Main FLS-H loop to improve a feasible solution.

        Args:
            x0: Initial feasible solution vector (diameter indexes).

        Returns:
            np.ndarray: The refined solution vector.
        """
        logger.info("[FLS-H] Starting Local Search Refinement...")
        
        x = x0.copy()
        best_eval = self.evaluate(x)
        
        if not best_eval['feasible']:
            logger.warning("[FLS-H] Started with an infeasible solution. Attempting to repair...")
            x = self.repair(x)
            best_eval = self.evaluate(x)
            if not best_eval['feasible']:
                logger.error("[FLS-H] Could not find a feasible starting point for refinement.")
                return x0

        best_cost = best_eval['cost']
        current_x = x.copy()
        current_cost = best_cost

        for i in range(self.max_iter):
            logger.debug(f"[FLS-H] Iteration {i+1}/{self.max_iter} | Best Cost: {best_cost:.2f}")
            
            vecinos = self.generate_neighborhood(current_x)
            
            # Apply repair and fast filters to candidates
            candidates = []
            for v in vecinos:
                v_repaired = self.repair(v)
                if self.is_promising(v_repaired, current_cost):
                    candidates.append(v_repaired)

            if not candidates:
                current_x = self.diversify(current_x)
                continue

            # Evaluate candidates
            eval_results = []
            for v in candidates:
                res = self.evaluate(v)
                if res['feasible']:
                    eval_results.append((v, res))

            if not eval_results:
                current_x = self.diversify(current_x)
                continue

            # Pick the best in neighborhood
            best_neigh_x, best_neigh_eval = min(eval_results, key=lambda item: item[1]['cost'])
            
            if best_neigh_eval['cost'] < best_cost:
                best_cost = best_neigh_eval['cost']
                x = best_neigh_x.copy()
                current_x = best_neigh_x.copy()
                current_cost = best_neigh_eval['cost']
            else:
                current_x, current_cost = self.accept_or_reject(current_x, current_cost, best_neigh_x, best_neigh_eval)

        logger.info(f"[FLS-H] Refinement complete. Final Cost: {best_cost:.2f}")
        return x

    def generate_neighborhood(self, x: np.ndarray) -> List[np.ndarray]:
        """Generates a list of valid neighboring solutions.

        Args:
            x: Current solution vector.

        Returns:
            List[np.ndarray]: List of neighboring solution vectors.
        """
        neighborhood = []
        n_vars = len(x)
        
        for _ in range(self.neighborhood_size):
            new_x = x.copy()
            # Mutate 1-2 random pipes
            n_mutations = np.random.randint(1, 3)
            indices = np.random.choice(n_vars, n_mutations, replace=False)
            
            for idx in indices:
                # Small perturbation: ±1 index
                step = 1 if np.random.random() > 0.5 else -1
                new_x[idx] = np.clip(new_x[idx] + step, self.simulation.lbound[idx], self.simulation.ubound[idx])
            
            neighborhood.append(new_x)
            
        return neighborhood

    def repair(self, x: np.ndarray) -> np.ndarray:
        """Hydraulic engineering repair rules."""
        repaired = np.round(x).astype(np.int32)
        repaired = np.clip(repaired, self.simulation.lbound, self.simulation.ubound)
        
        # Note: Advanced repair logic could use current pressure results to increase 
        # diameters of upstream critical pipes. For now, we ensure bounds are respected.
        return repaired


    def evaluate(self, x: np.ndarray) -> Dict[str, Any]:
        """Evaluates a solution using EPANET, with caching."""
        key = x.tobytes()
        if key in self.cache:
            return self.cache[key]

        # Run simulation
        self.simulation.set_x(x)
        cost = self.simulation.get_cost()
        feasible = self.simulation.check(mode='TF')
        # Propagate simulation count to the parent instance
        # (check() already increments simulation_cycles internally)
        
        result = {'cost': float(cost), 'feasible': bool(feasible)}
        self.cache[key] = result
        return result

    def is_promising(self, x: np.ndarray, current_cost: float) -> bool:
        """Heuristic to avoid simulating obviously bad results."""
        pipes = self.simulation.pipes
        catalog = self.simulation.catalog
        
        approx_cost = 0.0
        for i, pipe in enumerate(pipes):
            sn = str(pipe['series'])
            idx = int(x[i])
            approx_cost += float(pipe['length']) * float(catalog[sn][idx]['price'])
            
        # Accept if cost is lower or only slightly higher (to allow finding feasible paths)
        return approx_cost < (current_cost * (1.0 + self.acceptance_threshold))

    def accept_or_reject(self, current_x: np.ndarray, current_cost: float, 
                         new_x: np.ndarray, new_eval: Dict[str, Any]) -> Tuple[np.ndarray, float]:
        """Stochastic/Greedy acceptance logic."""
        if new_eval['cost'] < current_cost:
            return new_x.copy(), new_eval['cost']
        
        # Accept worsening within threshold to avoid local optima (30% chance)
        diff_percent = (new_eval['cost'] - current_cost) / current_cost
        if diff_percent <= self.acceptance_threshold and np.random.random() < 0.3:
            return new_x.copy(), new_eval['cost']
                
        return current_x, current_cost

    def diversify(self, x: np.ndarray) -> np.ndarray:
        """Perturb the solution more significantly to escape stagnation."""
        new_x = x.copy()
        n_vars = len(x)
        n_perturb = max(1, int(n_vars * 0.15))
        indices = np.random.choice(n_vars, n_perturb, replace=False)
        
        for idx in indices:
            jump = np.random.randint(1, 4) * (1 if np.random.random() > 0.5 else -1)
            new_x[idx] = np.clip(new_x[idx] + jump, self.simulation.lbound[idx], self.simulation.ubound[idx])
            
        return new_x
