package:
  name: ppno
  version: "0.3.1"

source:
  path: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - ppno = ppno.ppno:main

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - numpy >=1.20.0
    - scipy >=1.7.0
    - pygmo >=2.18.0

test:
  commands:
    - ppno --help

about:
  home: https://github.com/andresgciamtez/ppno
  license: Apache-2.0
  summary: 'Pressurized Pipe Network Optimizer'
  description: |
    PPNO is a tool for optimizing pressurized water pipe networks 
    using EPANET and evolutionary algorithms.
